name: fitman_app
description: Фитнес-менеджер App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.5.0
  shared_preferences: ^2.0.15
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.4
  intl: ^0.20.2
  fl_chart: ^1.1.1
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  flutter_dotenv: ^5.1.0
  web_socket_channel: ^2.4.0
  http_parser: ^4.1.2
  file_picker: ^8.0.0
  url_launcher: ^6.1.0
  riverpod_annotation: ^2.3.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed: ^2.5.2
  riverpod_generator: ^2.3.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env.dev
    - .env.prod
    - .env.test
    - .env.dev.mobile